package com.example.administrator.imclient.activity.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig smsDaoConfig;

    private final SmsDao smsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        smsDaoConfig = daoConfigMap.get(SmsDao.class).clone();
        smsDaoConfig.initIdentityScope(type);

        smsDao = new SmsDao(smsDaoConfig, this);

        registerDao(Sms.class, smsDao);
    }
    
    public void clear() {
        smsDaoConfig.getIdentityScope().clear();
    }

    public SmsDao getSmsDao() {
        return smsDao;
    }

}
